### ISSUE TITLE
1050, "Table 'user' already exists"

### ISSUE THREAD

**Issue by Volodymyrk** [dternyak/React-Redux-Flask#24] opened 2017-07-15 13:31 UTC
I believe python manage.py create_db creates "user" table, and the following command fails:

> sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1050, "Table 'user' already exists") [SQL: '\nCREATE TABLE user (\n\tid INTEGER NOT NULL AUTO_INCREMENT, \n\temail VARCHAR(255), \n\tpassword VARCHAR(255), \n\tPRIMARY KEY (id), \n\tUNIQUE (email)\n)\n\n']

So I had to manually `drop table user`, to follow the instruction.

**Comment by dternyak** [comment] 2017-07-23 06:14
Hello,

You likely already migrated your db, and forgot. Closing for now as I am unable to reproduce.

**Closed as completed by dternyak** 2017-07-23 06:15 UTC
